services:
  db:
    image: mysql:latest
    
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pokedex
      MYSQL_USER: erik
      MYSQL_PASSWORD: erik
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3310:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8089:80"
